services:
  forge:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FORGE_VERSION: ${FORGE_VERSION}
        MC_VERSION: ${MC_VERSION}
    container_name: forge-server
    ports:
      - "${SERVER_PORT}:25565"
    environment:
      - TZ=${TZ}
      - JVM_MIN_RAM=${JVM_MIN_RAM}
      - JVM_MAX_RAM=${JVM_MAX_RAM}
      - FORGE_VERSION=${FORGE_VERSION}
      - MC_VERSION=${MC_VERSION}
    volumes:
      - ./data/server.properties:/server/server.properties
      - ./data/entrypoint.sh:/server/entrypoint.sh
      - ./world:/server/world
      - ./backups:/backups
    stdin_open: true
    tty: true
    restart: unless-stopped
  
  backup:
    build:
      context: .
      dockerfile: Dockerfile.backup
      args:
        BACKUP_TIME: ${BACKUP_TIME}
    container_name: forge-backup
    volumes:
      - ./world:/server/world:ro
      - ./backups:/backups
    restart: unless-stopped